import React, { useState, useEffect } from 'react';
import { getOrderHistory } from '../services/api';
import { Clock, ExternalLink, X, MessageSquare, Receipt, Package, Trash2 } from 'lucide-react';
import { Order } from '../types';
import { PageHeader } from '../components/PageHeader';

const History: React.FC = () => {
    const [history, setHistory] = useState<Order[]>([]);
    const [selectedOrder, setSelectedOrder] = useState<Order | null>(null);

    useEffect(() => { fetchHistory(); }, []);

    const fetchHistory = async () => {
        try {
            const res = await getOrderHistory();
            setHistory(res.data);
        } catch (e) { console.error(e); }
    };

    return (
        <div className="space-y-12">
            <PageHeader
                title="Quotation Logs"
                subtitle="Review and manage all price quotations generated by customers."
            />

            {history.map((order) => (
                <div key={order._id} className="bg-white p-6 rounded-3xl border border-slate-100 shadow-sm flex flex-col sm:flex-row items-start sm:items-center justify-between gap-6 group hover:shadow-xl hover:-translate-y-1 transition-all duration-300">
                    <div className="flex items-center gap-6">
                        <div className="w-16 h-16 bg-slate-50 rounded-2xl flex items-center justify-center text-slate-400 group-hover:bg-indigo-50 group-hover:text-indigo-500 transition-colors shrink-0 shadow-inner">
                            <Clock className="w-8 h-8" />
                        </div>
                        <div>
                            <div className="flex items-center gap-3 mb-1">
                                <h4 className="font-black text-slate-800 tracking-tight">Quotation #{order._id.slice(-6).toUpperCase()}</h4>
                                <span className="text-[10px] font-black px-2.5 py-1 bg-indigo-50 text-indigo-600 rounded-lg uppercase tracking-widest">WHATSAPP</span>
                            </div>
                            <p className="text-xs text-slate-400 font-medium">{new Date(order.createdAt).toLocaleString()}</p>
                            <div className="flex flex-wrap gap-2 mt-3">
                                {order.items.slice(0, 3).map((item, i) => (
                                    <span key={i} className="text-[10px] font-bold px-3 py-1.5 bg-slate-50 text-slate-500 rounded-xl border border-slate-100">{item.name} <span className="text-indigo-400 ml-1">x{item.quantity}</span></span>
                                ))}
                                {order.items.length > 3 && <span className="text-[10px] font-bold px-3 py-1.5 bg-indigo-50 text-indigo-500 rounded-xl">+{order.items.length - 3} more items</span>}
                            </div>
                        </div>
                    </div>

                    <div className="text-right flex flex-col items-end gap-3 w-full md:w-auto self-stretch justify-between py-1">
                        <p className="text-2xl font-black text-slate-900 tracking-tight">Rs.{order.totalAmount.toLocaleString()}</p>
                        <button
                            onClick={() => setSelectedOrder(order)}
                            className="flex items-center gap-2 px-6 py-2.5 bg-slate-900 text-white rounded-2xl text-xs font-black shadow-lg shadow-slate-200 hover:bg-indigo-600 transition-all active:scale-95"
                        >
                            <span>Details</span>
                            <ExternalLink className="w-3.5 h-3.5" />
                        </button>
                    </div>
                </div>
            ))}

            {/* Quotation Details Modal */}
            {selectedOrder && (
                <div className="fixed inset-0 z-[60] flex items-center justify-center p-4 sm:p-6 lg:p-12 animate-in fade-in duration-300">
                    <div className="absolute inset-0 bg-slate-900/60 backdrop-blur-md" onClick={() => setSelectedOrder(null)} />
                    <div className="relative w-full max-w-4xl bg-white rounded-[40px] shadow-2xl overflow-hidden flex flex-col max-h-full animate-in zoom-in-95 duration-300">
                        {/* Modal Header */}
                        <div className="p-8 border-b border-slate-50 flex justify-between items-center bg-slate-50/50">
                            <div className="flex items-center gap-4">
                                <div className="w-12 h-12 bg-white rounded-2xl flex items-center justify-center text-indigo-500 shadow-sm border border-slate-100">
                                    <Receipt className="w-6 h-6" />
                                </div>
                                <div>
                                    <h2 className="text-2xl font-black text-slate-900 tracking-tight leading-none mb-1">Quotation Details</h2>
                                    <p className="text-xs text-slate-400 font-bold uppercase tracking-[0.2em]">Transaction #{selectedOrder._id.toUpperCase()}</p>
                                </div>
                            </div>
                            <button
                                onClick={() => setSelectedOrder(null)}
                                className="p-3 hover:bg-white bg-white/50 rounded-2xl transition-all shadow-sm active:scale-90 border border-slate-100"
                            >
                                <X className="w-6 h-6 text-slate-400" />
                            </button>
                        </div>

                        {/* Modal Content */}
                        <div className="p-8 overflow-y-auto space-y-10">
                            {/* Items Table */}
                            <div className="space-y-4">
                                <div className="flex items-center gap-2 mb-2">
                                    <Package className="w-4 h-4 text-slate-400" />
                                    <h3 className="text-[10px] font-black uppercase tracking-[0.2em] text-slate-400">Order Items</h3>
                                </div>
                                <div className="overflow-hidden rounded-3xl border border-slate-100 shadow-sm">
                                    <table className="w-full text-left">
                                        <thead className="bg-slate-50 text-[10px] font-black uppercase tracking-widest text-slate-400">
                                            <tr>
                                                <th className="px-6 py-4">Product Name</th>
                                                <th className="px-6 py-4">Price</th>
                                                <th className="px-6 py-4 text-center">Qty</th>
                                                <th className="px-6 py-4 text-right">Subtotal</th>
                                            </tr>
                                        </thead>
                                        <tbody className="divide-y divide-slate-50">
                                            {selectedOrder.items.map((item, i) => (
                                                <tr key={i} className="hover:bg-slate-50/50 transition-colors">
                                                    <td className="px-6 py-4">
                                                        <div className="flex items-center gap-3">
                                                            <div className="w-10 h-10 bg-slate-100 rounded-xl shrink-0 border border-slate-200/50" />
                                                            <div>
                                                                <p className="font-bold text-slate-800 text-sm italic">{item.name}</p>
                                                                <p className="text-[9px] text-slate-400 font-mono">{item.productCode}</p>
                                                            </div>
                                                        </div>
                                                    </td>
                                                    <td className="px-6 py-4 text-slate-600 font-bold text-sm italic">Rs.{item.price.toLocaleString()}</td>
                                                    <td className="px-6 py-4 text-center font-black text-slate-800 text-sm">{item.quantity}</td>
                                                    <td className="px-6 py-4 text-right font-black text-indigo-600 text-sm italic">Rs.{(item.price * item.quantity).toLocaleString()}</td>
                                                </tr>
                                            ))}
                                        </tbody>
                                        <tfoot className="bg-slate-50/50 border-t border-slate-100">
                                            <tr>
                                                <td colSpan={3} className="px-6 py-6 text-right font-black text-slate-500 uppercase tracking-widest text-xs">Grand Total</td>
                                                <td className="px-6 py-6 text-right font-black text-2xl text-slate-900 tracking-tighter italic">Rs.{selectedOrder.totalAmount.toLocaleString()}</td>
                                            </tr>
                                        </tfoot>
                                    </table>
                                </div>
                            </div>

                            {/* WhatsApp Message Section */}
                            {selectedOrder.whatsappMessage && (
                                <div className="space-y-4">
                                    <div className="flex items-center gap-2 mb-2">
                                        <MessageSquare className="w-4 h-4 text-slate-400" />
                                        <h3 className="text-[10px] font-black uppercase tracking-[0.2em] text-slate-400">Captured Message</h3>
                                    </div>
                                    <div className="p-8 bg-indigo-50/30 rounded-3xl border border-indigo-100/50 relative overflow-hidden group">
                                        <div className="absolute top-0 right-0 w-24 h-24 bg-indigo-500/5 rounded-full -mr-12 -mt-12 transition-transform group-hover:scale-125" />
                                        <p className="text-slate-600 text-sm leading-relaxed whitespace-pre-wrap font-medium relative italic">
                                            "{selectedOrder.whatsappMessage}"
                                        </p>
                                    </div>
                                </div>
                            )}
                        </div>

                        {/* Modal Footer */}
                        <div className="p-8 bg-slate-50 border-t border-slate-100 flex justify-end gap-4">
                            <button
                                className="px-8 py-3 bg-red-50 text-red-600 rounded-2xl font-black text-xs hover:bg-red-600 hover:text-white transition-all active:scale-95 flex items-center gap-2 shadow-sm shadow-red-100"
                            >
                                <Trash2 className="w-3.5 h-3.5" />
                                Delete Log
                            </button>
                            <button
                                onClick={() => setSelectedOrder(null)}
                                className="px-10 py-3 bg-slate-900 text-white rounded-2xl font-black text-xs hover:bg-indigo-600 transition-all active:scale-95 shadow-lg shadow-slate-200"
                            >
                                Close Details
                            </button>
                        </div>
                    </div>
                </div>
            )}

            {history.length === 0 && (
                <div className="text-center py-20 bg-white rounded-3xl border-2 border-slate-50 border-dashed italic text-slate-400">
                    No quotation history found.
                </div>
            )}
        </div>
    );
};

export default History;
